name: note_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animate_icons: ^1.0.0
  cached_network_image: ^2.5.0
  camera: ^0.7.0+2
  cloud_firestore: ^0.16.0
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  firebase_storage: ^7.0.0
  flutter_speed_dial: ^1.2.5
  flutter_spinkit: ^4.1.2+1
  flutter_svg: ^0.19.0
  font_awesome_flutter: ^8.11.0
  google_fonts: ^1.1.1
  google_sign_in: ^4.5.9
  image_picker: ^0.6.7+22
  intl: ^0.16.1
  path: ^1.7.0
  path_provider: ^1.6.27
  pedantic: ^1.9.2
  unicorndial: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/apple.svg
    - assets/email.svg
    - assets/google.svg
